[package]
name = "arcade-rs"
version = "0.1.0"
authors = ["Letheed <dev@daweb.se>"]
description = "Rust + SDL2 tutorial game by AydenKoans"
repository = "https://github.com/letheed/arcade-rs"
license = "MIT"
publish = false

[dependencies]
sdl2 = "0.25"
sdl2_image = "0.25"
time = "0.1"
